openapi: "3.0.0"
info:
  title: Pathfinder
  description: Generates routes for cargo shipping
  license:
    name: MIT
    url: https://github.com/dynamicguy/pathfinder/blob/master/LICENSE
paths:
  /paths:
    get:
      summary: Generates random paths between two locations.
      parameters:
        - name: from
          in: query
          description: Starting location
          required: true
          schema:
            type: string
        - name: to
          in: query
          description: Final location
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Route suggestions
          content:
            application/json:
              example: {
                "paths": [
                  {
                    "edges": [
                      {
                        "voyage": "0400S",
                        "origin": "SESTO",
                        "destination": "DEHAM",
                        "departure": "2015-11-14T23:19:07.249273439+01:00",
                        "arrival": "2015-11-15T18:19:07.249273439+01:00"
                      },
                      {
                        "voyage": "0100S",
                        "origin": "DEHAM",
                        "destination": "FIHEL",
                        "departure": "2015-11-17T17:57:07.249273439+01:00",
                        "arrival": "2015-11-18T21:59:07.249273439+01:00"
                      }
                    ]
                  },
                  {
                    "edges": [
                      {
                        "voyage": "0200T",
                        "origin": "SESTO",
                        "destination": "SEGOT",
                        "departure": "2015-11-14T16:44:07.249306459+01:00",
                        "arrival": "2015-11-15T11:35:07.249306459+01:00"
                      },
                      {
                        "voyage": "0200T",
                        "origin": "SEGOT",
                        "destination": "FIHEL",
                        "departure": "2015-11-17T19:05:07.249306459+01:00",
                        "arrival": "2015-11-18T22:54:07.249306459+01:00"
                      }
                    ]
                  },
                  {
                    "edges": [
                      {
                        "voyage": "0100S",
                        "origin": "SESTO",
                        "destination": "DEHAM",
                        "departure": "2015-11-14T12:22:07.249318801+01:00",
                        "arrival": "2015-11-15T15:51:07.249318801+01:00"
                      },
                      {
                        "voyage": "0301S",
                        "origin": "DEHAM",
                        "destination": "FIHEL",
                        "departure": "2015-11-17T15:06:07.249318801+01:00",
                        "arrival": "2015-11-18T07:38:07.249318801+01:00"
                      }
                    ]
                  },
                  {
                    "edges": [
                      {
                        "voyage": "0200T",
                        "origin": "SESTO",
                        "destination": "USNYC",
                        "departure": "2015-11-14T19:08:07.249330441+01:00",
                        "arrival": "2015-11-15T17:25:07.249330441+01:00"
                      },
                      {
                        "voyage": "0100S",
                        "origin": "USNYC",
                        "destination": "AUMEL",
                        "departure": "2015-11-17T11:13:07.249330441+01:00",
                        "arrival": "2015-11-18T17:30:07.249330441+01:00"
                      },
                      {
                        "voyage": "0300A",
                        "origin": "AUMEL",
                        "destination": "JNTKO",
                        "departure": "2015-11-20T21:11:07.249330441+01:00",
                        "arrival": "2015-11-22T02:08:07.249330441+01:00"
                      },
                      {
                        "voyage": "0301S",
                        "origin": "JNTKO",
                        "destination": "CNHGH",
                        "departure": "2015-11-24T05:52:07.249330441+01:00",
                        "arrival": "2015-11-25T12:56:07.249330441+01:00"
                      },
                      {
                        "voyage": "0400S",
                        "origin": "CNHGH",
                        "destination": "DEHAM",
                        "departure": "2015-11-27T23:49:07.249330441+01:00",
                        "arrival": "2015-11-29T01:51:07.249330441+01:00"
                      },
                      {
                        "voyage": "0400S",
                        "origin": "DEHAM",
                        "destination": "FIHEL",
                        "departure": "2015-12-01T09:52:07.249330441+01:00",
                        "arrival": "2015-12-02T07:09:07.249330441+01:00"
                      }
                    ]
                  }
                ]
              }
